# Generated by Django 4.0.6 on 2022-12-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseAPI', '0003_alter_note_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
