# Generated by Django 4.0.6 on 2022-12-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseAPI', '0004_remove_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='message',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
