# Generated by Django 4.0.6 on 2022-12-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseAPI', '0005_alter_note_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='message',
            field=models.CharField(blank=True, default='', max_length=100000, null=True),
        ),
    ]
